// Cloudflare Pages Function - Gemini + Imagen API Proxy
export async function onRequestPost(context) {
  const envKey = context.env.GEMINI_API_KEY;
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, X-API-Key',
  };

  try {
    const body = await context.request.json();
    const { prompt, model, aspect_ratio, apiKey, numberOfImages } = body;
    const GEMINI_API_KEY = apiKey || envKey;

    if (!GEMINI_API_KEY) {
      return new Response(JSON.stringify({ error: 'No API key. Set your Gemini key in Settings.' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    if (!prompt) {
      return new Response(JSON.stringify({ error: 'Prompt is required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Detect if Imagen model
    const isImagen = model && model.startsWith('imagen-');

    if (isImagen) {
      // Imagen API uses predict method
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:predict?key=${GEMINI_API_KEY}`;
      const imagenPayload = {
        instances: [{ prompt }],
        parameters: {
          sampleCount: numberOfImages || 1,
          aspectRatio: aspect_ratio || '1:1',
        }
      };

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(imagenPayload),
      });

      if (!response.ok) {
        const errText = await response.text();
        return new Response(JSON.stringify({ error: `Imagen API error: ${response.status}`, details: errText }), {
          status: response.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      const data = await response.json();
      const predictions = data.predictions || [];
      if (!predictions.length || !predictions[0].bytesBase64Encoded) {
        return new Response(JSON.stringify({ error: 'No image generated by Imagen.' }), {
          status: 422, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      // Return first image (or all if multiple)
      const images = predictions.map(p => ({
        url: `data:image/png;base64,${p.bytesBase64Encoded}`,
        mimeType: p.mimeType || 'image/png',
      }));

      return new Response(JSON.stringify({
        url: images[0].url,
        mimeType: images[0].mimeType,
        model,
        images: images.length > 1 ? images : undefined,
      }), {
        status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });

    } else {
      // Gemini generateContent (Nano Banana etc)
      let fullPrompt = prompt;
      if (aspect_ratio && aspect_ratio !== '1:1') {
        fullPrompt += ` [Aspect ratio: ${aspect_ratio}]`;
      }

      const geminiModel = model || 'gemini-2.5-flash-image';
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${geminiModel}:generateContent?key=${GEMINI_API_KEY}`;

      const geminiPayload = {
        contents: [{ parts: [{ text: fullPrompt }] }],
        generationConfig: { responseModalities: ['TEXT', 'IMAGE'] }
      };

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(geminiPayload),
      });

      if (!response.ok) {
        const errText = await response.text();
        return new Response(JSON.stringify({ error: `Gemini API error: ${response.status}`, details: errText }), {
          status: response.status, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      const data = await response.json();
      const parts = data.candidates?.[0]?.content?.parts || [];
      let imageData = null, textResponse = '';

      for (const part of parts) {
        if (part.inlineData) imageData = part.inlineData;
        if (part.text) textResponse += part.text;
      }

      if (!imageData) {
        return new Response(JSON.stringify({ error: 'No image generated.', text: textResponse }), {
          status: 422, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        });
      }

      return new Response(JSON.stringify({
        url: `data:${imageData.mimeType};base64,${imageData.data}`,
        mimeType: imageData.mimeType,
        text: textResponse,
        model: geminiModel,
      }), {
        status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
  } catch (err) {
    return new Response(JSON.stringify({ error: err.message }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
}

export async function onRequestOptions() {
  return new Response(null, {
    headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type, X-API-Key',
    },
  });
}
